#!/usr/bin/env python3
"""
gen_ahb_brom.py — Generate combinational AHB Boot ROM from $readmemh hex file

Usage:
    python3 gen_ahb_brom.py <input.hex> <output.v> [--depth N]
                            [--elf FILE] [--link-base 0xADDR]

Input:  $readmemh-format hex file (32-bit words, '@'-style address markers)
Output: Verilog ahb_brom module with always @(*) nested-case ROM

ASIC synthesis rationale:
    Follows ARM CMSDK sse050_rom_table.v / Corstone pattern.
    always @(*) case statement → synthesiser maps to MUX tree or mask ROM cells.
    No memory arrays, no 'initial' blocks — pure combinatorial standard-cell logic.
    'initial' is simulation-only and is silently IGNORED by Synopsys DC / Genus.

    The 10-bit address is split into upper [9:5] and lower [4:0] halves so that
    each inner case has ≤ 32 entries. This avoids a Verilator 5.028 trace-codegen
    runtime crash that occurs with large flat case statements.

    The only sequential element is the AHB address pipeline register (addr_lat),
    which captures HADDR during the address phase so HRDATA is valid one cycle
    later in the data phase — matching the AHB-Lite single-cycle subordinate spec.

    FPGA note: for FPGA targets use ahb_brom.v (common/brom/ahb_brom.v) which
    uses $readmemh + registered output so tools can infer Block RAM.
"""

import sys, argparse, subprocess, re

# ──────────────────────────────────────────────────────────────────────────────
# Verilog template  (CMSDK sse050_rom_table.v / nested-case pattern)
# ──────────────────────────────────────────────────────────────────────────────
HEADER = """\
// ahb_brom.v — AHB-Lite Boot ROM  (hardcoded, auto-generated)
//
// Generated by gen_ahb_brom.py from {hexfile}.
// DO NOT EDIT — re-run gen_ahb_brom.py to update.
//
// Interface identical to common/brom/ahb_brom.v (simulation/$readmemh model).
//
// ASIC synthesis note (Synopsys DC / Cadence Genus):
//   'initial' blocks are silently ignored by ASIC synthesis tools.
//   This file uses always @(*) nested-case instead — the standard ASIC
//   mask ROM pattern, following ARM CMSDK sse050_rom_table.v / Corstone style.
//   Synthesiser maps the case to a MUX tree or dedicated mask ROM cells.
//   No memory arrays, no flip-flop inference for ROM data.
//
//   The address is split addr_lat[{amsb}:5] (group) / addr_lat[4:0] (offset)
//   so each inner case has <= 32 entries (avoids sim-tool trace-codegen limits).
//
// Pipeline:
//   addr_lat (1 FF) captures haddr_i[{amsb_p2}:2] in the address phase.
//   hrdata_o is valid in the data phase (combinational from addr_lat).
//   hreadyout_o = 1 always (zero-wait-state, read-only subordinate).
//
// DEPTH  = {depth} words  ({bytes} bytes)
// Words  = {n_words} (non-zero: {n_nonzero})

`timescale 1ns/1ps

module ahb_brom #(
  parameter DEPTH = {depth}
) (
  input  wire        hclk_i,
  input  wire        hrst_ni,

  input  wire        hsel_i,
  input  wire        hready_i,
  input  wire [31:0] haddr_i,
  input  wire [1:0]  htrans_i,

  output wire        hreadyout_o,
  output wire [31:0] hrdata_o
);

  // ── Address pipeline register ─────────────────────────────────────────────
  reg [{amsb}:0] addr_lat;

  always @(posedge hclk_i or negedge hrst_ni) begin
    if (!hrst_ni)
      addr_lat <= {amsb_w}'h0;
    else if (hsel_i && hready_i && htrans_i[1])
      addr_lat <= haddr_i[{amsb_p2}:2];
  end

  // ── Combinational ROM (always @(*) nested case — ASIC mask ROM style) ────
  //
  //   Source: {hexfile}
  //   Pattern: ARM CMSDK sse050_rom_table.v / Corstone SSE-050
  //
  //   Outer case: addr_lat[{amsb}:5]  — 32-word group selector
  //   Inner case: addr_lat[4:0]       — word offset within group
  //   Each entry: value  // +byte_offset: disassembly mnemonic
  //
  reg [31:0] hrdata_r;
  always @(*) begin
    hrdata_r = 32'h00000000;
    case (addr_lat[{amsb}:5])
{cases}
      default: ;
    endcase
  end

  assign hrdata_o    = hrdata_r;
  assign hreadyout_o = 1'b1;

endmodule
"""

HEADER_FLAT = """\
// ahb_brom.v — AHB-Lite Boot ROM  (hardcoded, auto-generated)
//
// Generated by gen_ahb_brom.py from {hexfile}.
// DO NOT EDIT — re-run gen_ahb_brom.py to update.
//
// ASIC synthesis note: always @(*) case — no 'initial', no memory arrays.
//
// DEPTH  = {depth} words  ({bytes} bytes)
// Words  = {n_words} (non-zero: {n_nonzero})

`timescale 1ns/1ps

module ahb_brom #(
  parameter DEPTH = {depth}
) (
  input  wire        hclk_i,
  input  wire        hrst_ni,

  input  wire        hsel_i,
  input  wire        hready_i,
  input  wire [31:0] haddr_i,
  input  wire [1:0]  htrans_i,

  output wire        hreadyout_o,
  output wire [31:0] hrdata_o
);

  reg [{amsb}:0] addr_lat;

  always @(posedge hclk_i or negedge hrst_ni) begin
    if (!hrst_ni)
      addr_lat <= {amsb_w}'h0;
    else if (hsel_i && hready_i && htrans_i[1])
      addr_lat <= haddr_i[{amsb_p2}:2];
  end

  reg [31:0] hrdata_r;
  always @(*) begin
    case (addr_lat)
{cases}
      default: hrdata_r = 32'h00000000;
    endcase
  end

  assign hrdata_o    = hrdata_r;
  assign hreadyout_o = 1'b1;

endmodule
"""


# ──────────────────────────────────────────────────────────────────────────────
# Hex loader  ($readmemh format: '@addr' markers + space-separated hex words)
# ──────────────────────────────────────────────────────────────────────────────
def load_hex(path):
    words = {}
    cur = 0
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith('@'):
                cur = int(line[1:], 16)
            else:
                for tok in line.split():
                    words[cur] = int(tok, 16)
                    cur += 1
    return words


# ──────────────────────────────────────────────────────────────────────────────
# Disassembly parser  (arm-none-eabi-objdump -d)
# Returns: dict { word_idx -> "annotation string" }
#
# word_idx  = (linked_addr - link_base) >> 2
# For each 4-byte ROM word, collect all Thumb/Thumb-2 instructions that start
# within that word and format them as  "+0: MNEM  |  +2: MNEM".
# ──────────────────────────────────────────────────────────────────────────────
def get_disasm(elf_path, link_base):
    try:
        result = subprocess.run(
            ['arm-none-eabi-objdump', '-d', '--no-show-raw-insn', elf_path],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            universal_newlines=True, check=True
        )
    except FileNotFoundError:
        print('[gen_ahb_brom] arm-none-eabi-objdump not found — skipping annotations',
              file=sys.stderr)
        return {}
    except subprocess.CalledProcessError as e:
        print(f'[gen_ahb_brom] objdump failed: {e}', file=sys.stderr)
        return {}

    insn_map = {}
    for line in result.stdout.splitlines():
        # "10000080:	ldr	r0, [pc, #28]"
        m = re.match(r'\s*([0-9a-fA-F]+):\s+(.*)', line)
        if not m:
            continue
        addr_abs = int(m.group(1), 16)
        mnem     = m.group(2).strip()
        if not mnem:
            continue
        if addr_abs < link_base:
            continue
        byte_off = addr_abs - link_base
        insn_map[byte_off] = mnem

    annot = {}
    for byte_off, mnem in sorted(insn_map.items()):
        word_idx   = byte_off >> 2
        inword_off = byte_off & 3
        parts = annot.setdefault(word_idx, [])
        parts.append(f'+{inword_off}: {mnem}')

    return {k: '  |  '.join(v) for k, v in annot.items()}


# ──────────────────────────────────────────────────────────────────────────────
# Case builder — nested (amsb >= 5) or flat (amsb < 5)
# ──────────────────────────────────────────────────────────────────────────────
def build_nested_cases(words, depth, amsb, annot):
    """Group words by addr[amsb:5], emit nested case per group."""
    upper_w = amsb - 4          # bit-width of addr[amsb:5]

    groups = {}
    for idx in range(depth):
        val = words.get(idx, 0)
        if val == 0:
            continue
        upper = idx >> 5
        lower = idx & 0x1f
        groups.setdefault(upper, {})[lower] = val

    lines = []
    for upper in sorted(groups):
        lines.append(f"      {upper_w}'h{upper:02X}: begin")
        lines.append(f"        case (addr_lat[4:0])")
        for lower in sorted(groups[upper]):
            val = groups[upper][lower]
            idx = (upper << 5) | lower
            comment = f'  // {annot[idx]}' if idx in annot else ''
            lines.append(
                f"          5'h{lower:02X}: hrdata_r = 32'h{val:08X};{comment}"
            )
        lines.append("          default: ;")
        lines.append("        endcase")
        lines.append("      end")

    return '\n'.join(lines)


def build_flat_cases(words, depth, amsb_w, annot):
    """Simple flat case for small ROMs (depth <= 32)."""
    lines = []
    for idx in range(depth):
        val = words.get(idx, 0)
        if val == 0:
            continue
        comment = f'  // {annot[idx]}' if idx in annot else ''
        lines.append(
            f"      {amsb_w}'h{idx:02X}: hrdata_r = 32'h{val:08X};{comment}"
        )
    return '\n'.join(lines)


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('hexfile')
    ap.add_argument('outfile')
    ap.add_argument('--depth', type=int, default=1024,
                    help='ROM depth in 32-bit words (default 1024 = 4 KB)')
    ap.add_argument('--elf', default=None,
                    help='ELF file for disassembly annotations (optional)')
    ap.add_argument('--link-base', default='0x10000000',
                    help='Linked base address of ROM code (default 0x10000000)')
    args = ap.parse_args()

    words = load_hex(args.hexfile)
    if not words:
        print(f'ERROR: no data in {args.hexfile}', file=sys.stderr)
        sys.exit(1)

    link_base = int(args.link_base, 0)
    annot     = get_disasm(args.elf, link_base) if args.elf else {}

    depth  = args.depth
    amsb_w = len(bin(depth - 1)) - 2
    amsb   = amsb_w - 1

    n_nonzero = sum(1 for idx in range(depth) if words.get(idx, 0) != 0)

    if amsb >= 5:
        cases   = build_nested_cases(words, depth, amsb, annot)
        tmpl    = HEADER
    else:
        cases   = build_flat_cases(words, depth, amsb_w, annot)
        tmpl    = HEADER_FLAT

    verilog = tmpl.format(
        hexfile   = args.hexfile,
        depth     = depth,
        amsb      = amsb,
        amsb_w    = amsb_w,
        amsb_p2   = amsb + 2,
        bytes     = depth * 4,
        n_words   = len(words),
        n_nonzero = n_nonzero,
        cases     = cases,
    )

    with open(args.outfile, 'w') as f:
        f.write(verilog)

    print(f'[gen_ahb_brom] {len(words)} words → {args.outfile}  '
          f'(DEPTH={depth}, non-zero={n_nonzero}, annotated={len(annot)})')


if __name__ == '__main__':
    main()
